Second homework done
MartinCherry/my_codelex_things pull request #2
Opened 2022-09-10 11:01 UTC by MartinCherry

2022-09-23 20:00 UTC, NilsKula requested changes
labi :+1:

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +        if (n >= 1000000000L) {
te jau bija jāpārbauda vai ir long :thinking:

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/AsciiFigure.java
> +    String leftSide = "/";
ciparus, kam nemaini vērtību var izvilkt tad labāk ārā kā konstantes

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/AsciiFigure.java
> +        for (int i = 0; i<number;i++) {
foramtting, spacing

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/Excercise_05.java
> +        int totalWidth = 30;
labi, ka atsevišķi apzīmē, bet šo arī varētu uz klases līmeni

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/Excercise_05.java
> +public class Excercise_05 {
klases bez undersore

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/Exercise_07.java
> +                }
`} else {`

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/Exercise_07.java
> +                    totalScore = 1;
piešķir viens, bet pēctam jau vairs nekur nezinamto :thinking:

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/NumberSquare.java
> +                if (n > max)
formatting
```
if () {
 foo
}

2022-09-23 20:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/RollTwoDice.java
> +            int a = randomer.nextInt(1, 7);
varētu izvilkt uz palīgmetodi, jo atkāŗtojas, piemēŗam, `.rollDice()`
un izvairies no viena burta variabļu apzīmejumiem

2022-09-24 11:15 UTC, MartinCherry commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/Exercise_07.java
> +                }
Īsti nesaprotu kas ar šo ir domāts?

2022-09-24 11:16 UTC, MartinCherry commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/Exercise_07.java
> +                }
Ja kļūda ir tajā, ka else ir tajā pašā rindā, kur aizverošās if iekavas, tad man automātiski tā pārformatē pēk katra save.

2022-09-30 16:00 UTC, NilsKula commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/Exercise_07.java
> +                }
jā par to, pēc 'convention' vajadzetu būt tā, settingos noteitki var pamainīt, bet nav arī tik būtiski

2022-09-30 16:00 UTC, NilsKula approved these changes

2022-09-30 16:03 UTC, MartinCherry commented on homeworks-05-2022/src/main/java/io/codelex/loops/practice/Exercise_07.java
> +                }
Paldies. Atradu. Ieķeksēju.

2022-09-30 18:21 UTC, merged